# models/staging/schema.yml

version: 2

models:
  - name: stg_products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: stg_transactions
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique

  - name: stg_locations
    columns:
      - name: location_id
        tests:
          - not_null
          - unique

  - name: stg_stores
    columns:
      - name: store_id
        tests:
          - not_null
          - unique
